config/routes.rb
Rails.application.routes.draw do

  root 'albums#index'

  get 'cadastro' => 'users#new'
  resources :users

  get 'login' => 'sessions#new'
  resources :sessions

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  get 'albums' => 'albums#index'
  get 'albums/:id' => 'albums#show', as: :album
  resources :albums

  resources :photos, only: [:show, :edit, :update, :destroy]

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :photo
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  def editor?
    self.role == "editor"
  end

  def admin?
    self.role == "admin"
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action :require_user, only: [:index, :show]

  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
    @photos = @album.photo
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  before_action :clear_my_cache

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end

  def require_editor
    redirect_to '/' unless current_user.editor?
  end

  def require_admin
    redirect_to '/' unless current_user.admin?
  end

  def clear_my_cache
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  before_action :require_user, only: [:show, :edit, :update, :destroy]
  #before_action :require_editor, only: [:show, :edit]
  #before_action :require_admin, only: [:destroy]

  def show
    @photo = Photo.find(params[:id])
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
      if @photo.update(photo_params)
        redirect_to @photo
      else
        render 'edit'
      end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to root_url
  end

  private
  def photo_params
    params.require(:photo).permit(:caption, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/cadastro'
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/index.html.erb
<div class="albums">
  <div class="container">

    <div class="row">
      <% @albums.each do |album| %> 
        <div class="item col-md-4">
          <div class="img-container">
            <%= image_tag album.image %>
          </div>
          <div class="album-info">
            <h2><%= album.title %></h2>
            <p><%= link_to "See Album", album_path(album) %></p>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/albums/show.html.erb
<div class="photos">
  <div class="container">

    <h1>Album de fotos: <%= @album.title %></h1>
    <div class="row">
      <% @photos.each do |photo| %>
        <div class="item col-md-4">
          <div class="img-container">
            <%= image_tag photo.image %>
          </div>
          <div class="photo-info">
            <p><%= photo.caption %></p>
            <p class="photo-link"><%= link_to "Show Photo", photo_path(photo) %></p>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsAuthorization</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user %>
    <ul>
      <li><%= current_user.email %></li>
      <li><%= link_to "Log out", logout_path, method: "delete" %></li>
    </ul>
  <% else %>
    <ul>
      <li><%= link_to "Login", 'login' %></a></li>
      <li><%= link_to "Cadastre-se", 'cadastro' %></a></li> 
    </ul>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/photos/edit.html.erb
<div class="photo-edit">
  <div class="container">
    <div class="img_container">
      <%= image_tag @photo.image %>
    </div>

    <%= form_for(@photo) do |f| %>
      <%= f.text_area :caption %>
      <%= f.submit "Update", :class => "form-btn" %>
    <% end %>

  </div>
</div>

app/views/photos/show.html.erb
<div class="img_container">
  <%= image_tag @photo.image %>
</div>
<div class="photo-info">
  <p class="caption"><%= @photo.caption %></p>
</div>

<% if current_user && current_user.editor? %>
  <p class="recipe-edit">
    <%= link_to "Edit Photo", edit_photo_path(@photo.id) %>
  </p>
<% end %>

<% if current_user && current_user.admin? %> 
  <p class="photo-delete"><%= link_to "Delete", photo_path(@photo), method: "delete" %><p>
<% end %>

app/views/users/new.html.erb
<div class="login">
  <div class="container">
    <div class="form">

    <h1>Cadastre-se</h1>
    <%= form_for(@user) do |f| %>
      <%= f.text_field :first_name, :placeholder => "Nome" %>
      <%= f.text_field :last_name, :placeholder => "Sobrenome" %>
      <%= f.text_field :email, :placeholder => "E-mail" %>
      <%= f.password_field :password, :placeholder => "Senha" %>
      <%= f.submit "Cadastrar" %>
    <% end %>
    </div>
  </div>
</div>